name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  repository_dispatch:
  workflow_dispatch:
env:
  test_user: users/joey-1st
  test_time: 2024.10.18
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${test_user}
          echo ${test_time} 
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: configure
        run:
          chmod +x configure
          ./configure
      - name: make
        run: make
      - name: test
        run: ./test
      - name: Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: prebuild_driver
          body: test demo
          files: test
      - name: clean
        run: make clean
